import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ThemeProvider } from "@/components/theme-provider";
import { LanguageSwitcher } from "@/components/language-switcher";
import { ModeToggle } from "@/components/modeToggle/modeToggle";
import Providers from "@/providers/providers";
import "./globals.css";
import NavBar from "@/components/navBar/navBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Providers>
      <html
        lang="en"
        suppressHydrationWarning
      >
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <div className="flex flex-col min-h-screen">
              <header className="sticky top-0 z-40 w-full border-b bg-background">
                <NavBar />
              </header>

              <main className="flex-grow">{children}</main>

              <footer className="w-full border-t bg-background py-6">
                <div className="container flex items-center justify-center">
                  <p>
                    &copy; {new Date().getFullYear()} Sebastian Danilo Narvaez
                    Narvaez. All rights reserved.
                  </p>
                </div>
              </footer>
            </div>
          </ThemeProvider>{" "}
        </body>
      </html>
    </Providers>
  );
}
